version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: in-memory-cache-php
    image: in-memory-cache-php
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
